name: firestr
version: '0.11.1'
summary: The Grass Computing Platform
description: |
    Communicate with your friends and family over a secure P2P connection.
    Create and share P2P applications easily using the Lua programming language.

grade: stable
confinement: strict
icon: src/gui/resources/firestr.svg

parts:
  firestr:
    source: .
    plugin: cmake
    build-packages:
        - qtbase5-dev  
        - qtmultimedia5-dev
        - libqt5svg5-dev
        - libboost-system-dev
        - libboost-program-options-dev
        - libboost-filesystem-dev
        - libboost-regex-dev
        - libboost-thread-dev
        - uuid-dev
        - libgmp-dev
        - libssl-dev
        - libxss-dev
        - libbotan1.10-dev
        - libopus-dev
        - libsnappy-dev
    stage-packages:
        - libpulse0
        - libasound2
        - locales-all
        - libqt5core5a
        - libqt5svg5
        - libqt5widgets5
        - libqt5network5
        - libqt5multimedia5
        - libqt5multimedia5-plugins
        - libqt5multimediawidgets5
    after: [qt5conf]

apps:
    firestr:
        command: qt5-launch firestr
        desktop: share/applications/firestr.desktop
        plugs: [unity7, home, opengl, alsa, pulseaudio, network, network-bind]
